//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petersilie.ManagementTools.NetworkMonitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petersilie.ManagementTools.NetworkMonitor.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo reply.
        /// </summary>
        internal static string ICMP_000_00 {
            get {
                return ResourceManager.GetString("ICMP_000_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ICMP_001_00 {
            get {
                return ResourceManager.GetString("ICMP_001_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ICMP_002_00 {
            get {
                return ResourceManager.GetString("ICMP_002_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination network unreachable.
        /// </summary>
        internal static string ICMP_003_00 {
            get {
                return ResourceManager.GetString("ICMP_003_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination host unreachable.
        /// </summary>
        internal static string ICMP_003_01 {
            get {
                return ResourceManager.GetString("ICMP_003_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination protocol unreachable.
        /// </summary>
        internal static string ICMP_003_02 {
            get {
                return ResourceManager.GetString("ICMP_003_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination port unreachable.
        /// </summary>
        internal static string ICMP_003_03 {
            get {
                return ResourceManager.GetString("ICMP_003_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation required, and DF flag set.
        /// </summary>
        internal static string ICMP_003_04 {
            get {
                return ResourceManager.GetString("ICMP_003_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source route failed.
        /// </summary>
        internal static string ICMP_003_05 {
            get {
                return ResourceManager.GetString("ICMP_003_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination network unkown.
        /// </summary>
        internal static string ICMP_003_06 {
            get {
                return ResourceManager.GetString("ICMP_003_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination host unkown.
        /// </summary>
        internal static string ICMP_003_07 {
            get {
                return ResourceManager.GetString("ICMP_003_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source host isolated.
        /// </summary>
        internal static string ICMP_003_08 {
            get {
                return ResourceManager.GetString("ICMP_003_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network administratively prohibited.
        /// </summary>
        internal static string ICMP_003_09 {
            get {
                return ResourceManager.GetString("ICMP_003_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host administratively prohibited.
        /// </summary>
        internal static string ICMP_003_10 {
            get {
                return ResourceManager.GetString("ICMP_003_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network unreachable for ToS.
        /// </summary>
        internal static string ICMP_003_11 {
            get {
                return ResourceManager.GetString("ICMP_003_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host unreachable for ToS.
        /// </summary>
        internal static string ICMP_003_12 {
            get {
                return ResourceManager.GetString("ICMP_003_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication administratively prohibited.
        /// </summary>
        internal static string ICMP_003_13 {
            get {
                return ResourceManager.GetString("ICMP_003_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Precedence Violation.
        /// </summary>
        internal static string ICMP_003_14 {
            get {
                return ResourceManager.GetString("ICMP_003_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precedence cutoff in effect.
        /// </summary>
        internal static string ICMP_003_15 {
            get {
                return ResourceManager.GetString("ICMP_003_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciated.
        /// </summary>
        internal static string ICMP_004_00 {
            get {
                return ResourceManager.GetString("ICMP_004_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Datagram for Network.
        /// </summary>
        internal static string ICMP_005_00 {
            get {
                return ResourceManager.GetString("ICMP_005_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Datagram for Host.
        /// </summary>
        internal static string ICMP_005_01 {
            get {
                return ResourceManager.GetString("ICMP_005_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Datagram for the ToS and network.
        /// </summary>
        internal static string ICMP_005_02 {
            get {
                return ResourceManager.GetString("ICMP_005_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Datagram for the ToS and host.
        /// </summary>
        internal static string ICMP_005_03 {
            get {
                return ResourceManager.GetString("ICMP_005_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciated.
        /// </summary>
        internal static string ICMP_006_00 {
            get {
                return ResourceManager.GetString("ICMP_006_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        internal static string ICMP_007_00 {
            get {
                return ResourceManager.GetString("ICMP_007_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo request.
        /// </summary>
        internal static string ICMP_008_00 {
            get {
                return ResourceManager.GetString("ICMP_008_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router Advertisment.
        /// </summary>
        internal static string ICMP_009_00 {
            get {
                return ResourceManager.GetString("ICMP_009_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router discovery/selection/solicitation.
        /// </summary>
        internal static string ICMP_010_00 {
            get {
                return ResourceManager.GetString("ICMP_010_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTL expired in transit.
        /// </summary>
        internal static string ICMP_011_00 {
            get {
                return ResourceManager.GetString("ICMP_011_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment reassembly time exceeded.
        /// </summary>
        internal static string ICMP_011_01 {
            get {
                return ResourceManager.GetString("ICMP_011_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer indicates the error.
        /// </summary>
        internal static string ICMP_012_00 {
            get {
                return ResourceManager.GetString("ICMP_012_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing a required option.
        /// </summary>
        internal static string ICMP_012_01 {
            get {
                return ResourceManager.GetString("ICMP_012_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad length.
        /// </summary>
        internal static string ICMP_012_02 {
            get {
                return ResourceManager.GetString("ICMP_012_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string ICMP_013_00 {
            get {
                return ResourceManager.GetString("ICMP_013_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp reply.
        /// </summary>
        internal static string ICMP_014_00 {
            get {
                return ResourceManager.GetString("ICMP_014_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information request.
        /// </summary>
        internal static string ICMP_015_00 {
            get {
                return ResourceManager.GetString("ICMP_015_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information reply.
        /// </summary>
        internal static string ICMP_016_00 {
            get {
                return ResourceManager.GetString("ICMP_016_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address mask request.
        /// </summary>
        internal static string ICMP_017_00 {
            get {
                return ResourceManager.GetString("ICMP_017_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address mask reply.
        /// </summary>
        internal static string ICMP_018_00 {
            get {
                return ResourceManager.GetString("ICMP_018_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for security.
        /// </summary>
        internal static string ICMP_019_00 {
            get {
                return ResourceManager.GetString("ICMP_019_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information request.
        /// </summary>
        internal static string ICMP_030_00 {
            get {
                return ResourceManager.GetString("ICMP_030_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datagram conversion error.
        /// </summary>
        internal static string ICMP_031_00 {
            get {
                return ResourceManager.GetString("ICMP_031_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile host redirect.
        /// </summary>
        internal static string ICMP_032_00 {
            get {
                return ResourceManager.GetString("ICMP_032_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where-Are-You (originally meant for IPv6).
        /// </summary>
        internal static string ICMP_033_00 {
            get {
                return ResourceManager.GetString("ICMP_033_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here-I-Am (originally meant for IPv6).
        /// </summary>
        internal static string ICMP_034_00 {
            get {
                return ResourceManager.GetString("ICMP_034_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile registration request.
        /// </summary>
        internal static string ICMP_035_00 {
            get {
                return ResourceManager.GetString("ICMP_035_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile registration reply.
        /// </summary>
        internal static string ICMP_036_00 {
            get {
                return ResourceManager.GetString("ICMP_036_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name request.
        /// </summary>
        internal static string ICMP_037_00 {
            get {
                return ResourceManager.GetString("ICMP_037_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name reply.
        /// </summary>
        internal static string ICMP_038_00 {
            get {
                return ResourceManager.GetString("ICMP_038_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIP algorithm discovery protocol, simple key-management for internet protocol.
        /// </summary>
        internal static string ICMP_039_00 {
            get {
                return ResourceManager.GetString("ICMP_039_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photuris, Security failures.
        /// </summary>
        internal static string ICMP_040_00 {
            get {
                return ResourceManager.GetString("ICMP_040_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP for experimental mobility protocol such as Seamoby.
        /// </summary>
        internal static string ICMP_041_00 {
            get {
                return ResourceManager.GetString("ICMP_041_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request extended echo (XPing).
        /// </summary>
        internal static string ICMP_042_00 {
            get {
                return ResourceManager.GetString("ICMP_042_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        internal static string ICMP_043_00 {
            get {
                return ResourceManager.GetString("ICMP_043_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed query.
        /// </summary>
        internal static string ICMP_043_01 {
            get {
                return ResourceManager.GetString("ICMP_043_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such interface.
        /// </summary>
        internal static string ICMP_043_02 {
            get {
                return ResourceManager.GetString("ICMP_043_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such table entry.
        /// </summary>
        internal static string ICMP_043_03 {
            get {
                return ResourceManager.GetString("ICMP_043_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple interfaces satisfy query.
        /// </summary>
        internal static string ICMP_043_04 {
            get {
                return ResourceManager.GetString("ICMP_043_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for robustness experiment.
        /// </summary>
        internal static string ICMP_20To29 {
            get {
                return ResourceManager.GetString("ICMP_20To29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC3692-style Experiment 1 (RFC 4727).
        /// </summary>
        internal static string ICMP_253_00 {
            get {
                return ResourceManager.GetString("ICMP_253_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC3692-style Experiment 2 (RFC 4727).
        /// </summary>
        internal static string ICMP_254_00 {
            get {
                return ResourceManager.GetString("ICMP_254_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ICMP_255_00 {
            get {
                return ResourceManager.GetString("ICMP_255_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ICMP_44To252 {
            get {
                return ResourceManager.GetString("ICMP_44To252", resourceCulture);
            }
        }
    }
}
